### ISSUE TITLE
Plugin hangs in load() function - ROS Melodic

### ISSUE THREAD

**Issue by tandronescu** [roboticsgroup/roboticsgroup_gazebo_plugins#20] opened 2020-07-27 17:42 UTC
It appears that the plugin is hanging inside the load() function. More specifically where the ros nodehandle is created:
`ros::NodeHandle model_nh(robot_namespace_);`

I can comment it out and use the plugin without PID but to use PID a node handle is required. Otherwise the load function just freezes there and does not complete.

**Comment by nlamprian** [comment] 2020-07-27 18:49
I would assume you are referring to [line 91](https://github.com/roboticsgroup/roboticsgroup_gazebo_plugins/blob/master/src/mimic_joint_plugin.cpp#L91) and not [line 66](https://github.com/roboticsgroup/roboticsgroup_gazebo_plugins/blob/master/src/mimic_joint_plugin.cpp#L66). model_nh does not depend on whether the pid is enabled or not.

Questions that can shine some light:
* Are you launching gazebo through gazebo_ros?
* What is the plugin configuration you have specified?
* Do you see any errors in the log?

There is nothing special about creating a node handle. As long as there is a ros node initialized, it should just work.

**Comment by tandronescu** [comment] 2020-07-27 19:17
No, I am actually referring to line 66, which runs regardless of pid enabled/disabled.

1. Yes I am launching gazebo through gazebo ros. I also tested it with roscore running.
2. Here is the configuration for my mimic joint: 
`has_pid="true" multiplier="-1.0" max_effort="10.0"
    robot_namespace="my_robot_ns" `

3. No errors, it appears to hang. I put debug statements immediately after line 66 and it does not reach there. Running it in debug gives no other clues.

Hm, okay might be something weird on my machine. I have a gazebo_ros_control plugin running as well and it correctly goes through its load function and creates the node handle it needs.

**Comment by nlamprian** [comment] 2020-08-15 10:39
Closing the ticket as the problem is not plugin related.

**Closed as completed by nlamprian** 2020-08-15 10:39 UTC
